version: '2'
services:
  data:
    image: onnimonni/unison:2.48.4
    environment:
      UNISON_DIR: /app
      UNISON_UID: 1000
      UNISON_GID: 1001
    volumes:
      - /app
    ports:
      - "5000"

  web:
      image: geniem/dashboard
      ports:
        - 1337
      links:
        - redis
        - db
      depends_on:
        - redis
        - db
        - data
      volumes_from:
        - data
      environment:
        NODE_ENV: development
        HOSTNAME: sb.test
        VIRTUAL_HOST: sb.test
        VIRTUAL_PORT: 1337
        HTTPS_HOST: sb.test
      
  db:
      image: mongo
      volumes:
        - /data/db

  redis:
      image: redis

